"""Add Community model and relationship to ChatRoom

Revision ID: eb7188de4543
Revises: 52347d43af1b
Create Date: 2025-09-04 17:04:56.483528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.exc import OperationalError


# revision identifiers, used by Alembic.
revision = 'eb7188de4543'
down_revision = '52347d43af1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table('community',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('cover_image', sa.String(length=150), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )
    except OperationalError as e:
        if "table community already exists" not in str(e):
            raise

    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_chat_room_community_id', 'community', ['community_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_room_community_id', type_='foreignkey')
        batch_op.drop_column('community_id')

    op.drop_table('community')
    # ### end Alembic commands ###
